### PR TITLE
Fix duplicate out_dir in update_fasta

### LINKED ISSUE #81: mob_cluster: Duplicated path during copy of 'references_updated.fasta' file
The `update_fasta` variable is initialized here as the `out_dir/references_updated.fasta`:

https://github.com/phac-nml/mob-suite/blob/40ec14b7322d4d0ad8506a65b77e28275b826fe0/mob_suite/mob_cluster.py#L566

...then when it is used here for a file copy, the `out_dir` is prepended again:

https://github.com/phac-nml/mob-suite/blob/40ec14b7322d4d0ad8506a65b77e28275b826fe0/mob_suite/mob_cluster.py#L623

...resulting in `out_dir/out_dir/references_updated.fasta`, which is giving an error:

```
FileNotFoundError: [Error 2] No such file or directory: 'out_dir/out_dir/references_updated.fasta
```

### PR DESCRIPTION
**Pull request by dfornika**
Fixes #81

### CODE REVIEW

**Comment by kbessonov1984** [comment]
Looks good to me. Indeed variable `update_fasta` variable already has `out_dir` path incorporated, so there is no need to specify it again. I approve this bug fix. Thank you for helping us. Should be part of the next MOB-Suite release soon.

**Comment by dfornika** [comment]
Ok great. Are you able to merge this?

**Comment by kbessonov1984** [comment]
@dfornika  Sorry for delay. Will do merge on Monday.  Just need to double check in my docker container.

**Comment by kbessonov1984** [comment]
Tested in docker container an indeed this issue was preventing `mob_cluster` to successfully write `references_updated.fasta` file as extra path depth was specified pointing to non-existing output folder. This issue was only seen in `update` mode

**Pull request merged**
